---
# This playbook will install Microsoft SQL Server 
# Some code is based on
#  https://github.com/htaira/ansible-role-mssql-server

- name: Enable the Microsoft Signing Key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Enable the Microsoft SQL repository
  get_url:
    url: https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo
    dest: /etc/yum.repos.d/mssql-server.repo

- name: Install Microsoft SQL package
  yum: name={{ item }} state=installed
  with_items:
   - mssql-server

- name: Execute mssql-conf
  command: /opt/mssql/bin/mssql-conf -n setup
  args:
    creates: /var/opt/mssql/mssql.conf
  environment:
    ACCEPT_EULA: "y"
    MSSQL_PID: "{{ product_id }}"
    MSSQL_SA_PASSWORD: "{{ sa_password }}"

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mssql_port }}/tcp permanent=true state=enabled immediate=yes

