---
# This playbook will install Microsoft SQL Server and create db user and give permissions.

- name: Enable the Microsoft SQL repository
  get_url:
    url=https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo
    dest=/etc/yum.repos.d/mssql-server.repo

- name: Install Microsoft SQL package
  yum: name={{ item }} state=installed
  with_items:
   - mssql-server

#- name: Configure #SELinux to start mysql on any port
  #seboolean: name=mysql_connect_any state=true persistent=yes

#- name: Create Mysql configuration file
  #template: src=my.cnf.j2 dest=/etc/my.cnf
  #notify:
  #- restart mssql

#- name: Create MariaDB log file
  #file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

#- name: Create MariaDB PID directory
  #file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  #service: name={{ mssqlservice }} state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mssql_port }}/tcp permanent=true state=enabled immediate=yes

#- name: Create Application Database
  #mysql_db: name={{ dbname }} state=present

#- name: Create Application DB User
  #mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
